version: '3.1'

services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_DATABASE: admin
      MONGODB_USER: root
      MONGODB_PASS: mongoadmin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/gettingstarted
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration

  mongodb:
    image: tutum/mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: admin
      MONGODB_USER: user
      MONGODB_PASS: mongoadmin
    volumes:
      - ./init-db/init-db.js:/docker-entrypoint-initdb.d/init-db.js
      - ./data-db:/data/db

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/gettingstarted
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/gettingstarted
    links:
      - mongodb
    depends_on:
      - mongodb


